### ISSUE TITLE
Readme shows macros have wrong capitalization

### ISSUE THREAD

**Issue by ggggggggg** [JuliaArbTypes/TypedDelegation.jl#1]
Readme says `@delegate_onefield` but the actual macro name appears to be `@delegate_oneField`. Likewise for the other macros.

**Comment by JeffreySarnoff** [comment]
Hi -- and thank you.  It's a release mismatch.  I will get it sorted.

**Comment by JeffreySarnoff** [comment]
just pushed release should be good
