### ISSUE TITLE
Is there a recommended replacement?

### ISSUE THREAD

**Issue by ggggggggg** [JuliaArbTypes/TypedDelegation.jl#4]
Just noticed you changed this to say OBSOLETE.

**Comment by JeffreySarnoff** [comment]
Wish there were!  I expect trouble with v0.7, and the problems are not easy for me to remedy.  If you want -- have a look.

**Comment by JeffreySarnoff** [comment]
And now there is! Please replace `using TypedDelegation` with ... `using TypedDelegation`.    
(planned obsolescence is *revoked*).

**Comment by ggggggggg** [comment]
Great!
